(function () {
  window.CatGame = window.CatGame || {
    config: {
      storageKey: "catGameSaveV1",
      version: "1.15.2",
      startingFurniture: ["bed_basic", "bowl_basic"],
      releaseNotes: {
        "zh-CN": [
          "彩票系统新增历史购票查询，可按每一期查看当时买过的全部号码与中奖结果。",
          "历史购票查询会同时显示当前期、待开奖期和已开奖期，方便回看每次下注记录。",
          "版本说明继续保持只显示当前版本内容，避免旧版本文案持续堆积。",
        ],
        en: [
          "The Lottery system now includes a ticket history query so you can review every number bought for each draw.",
          "Ticket history shows current, pending, and resolved draw periods, along with ticket outcomes when available.",
          "The Version page still keeps only the current release notes so old notes do not keep piling up.",
        ],
        ja: [
          "宝くじに購入履歴検索を追加し、各抽選回で買った番号をまとめて確認できるようになりました。",
          "購入履歴では現在の回、保留中の回、確定済みの回をまとめて確認できます。",
          "バージョンページは引き続き現在の更新内容だけを表示し、古い説明が増え続けないようにしています。",
        ],
      },
      readoptCost: 80,
      toyWandUsesPerPurchase: 6,
      catUnlockRequirements: {
        gold: 5000,
        baseCatId: "cat_001",
        baseAgeYears: 1,
      },
      catAgeAcceleration: 10,
      pregnancyDurationMs: 30 * 60 * 1000,
      pregnancyFoodMultiplier: 2,
      roomUpgradeSteps: [
        { level: 1, capacity: 3, width: 620, height: 360, upgradeCost: 450 },
        { level: 2, capacity: 4, width: 760, height: 420, upgradeCost: 900 },
        { level: 3, capacity: 5, width: 900, height: 500, upgradeCost: 1600 },
        { level: 4, capacity: 6, width: 1020, height: 580, upgradeCost: null },
      ],
      diseaseCheckIntervalMs: 15 * 60 * 1000,
      staminaRecoveryIntervalMs: 60 * 60 * 1000,
      staminaRecoveryAmount: 5,
      customMusicMaxBytes: 2 * 1024 * 1024,
      slotBets: [20, 50, 100],
      playerCondition: {
        min: 0,
        max: 100,
        defaultStamina: 100,
        defaultMood: 80,
        defaultHunger: 20,
        hungerBlockThreshold: 80,
        hungerIncreaseIntervalMs: 15 * 60 * 1000,
        hungerIncreaseAmount: 4,
        sleepRecoveryPerHour: {
          stamina: 20,
          mood: 20,
        },
        workMoodThresholds: {
          normal: 60,
          tired: 30,
        },
        workMoodModifiers: {
          normal: {
            durationMultiplier: 1,
            penaltyChance: 0,
            penaltyRange: [0, 0],
          },
          tired: {
            durationMultiplier: 1.25,
            penaltyChance: 0,
            penaltyRange: [0, 0],
          },
          burnedOut: {
            durationMultiplier: 1.5,
            penaltyChance: 0.2,
            penaltyRange: [0.1, 0.2],
          },
        },
        moodLevels: [
          { min: 80, key: "player_mood_very_good", tone: "is-good" },
          { min: 60, key: "player_mood_good", tone: "is-success" },
          { min: 30, key: "player_mood_tired", tone: "is-warning" },
          { min: 0, key: "player_mood_burned_out", tone: "is-danger" },
        ],
      },
      bank: {
        minLoanAmount: 100,
        maxLoanAmount: 2000,
        savingsDailyRate: 0.01,
        dailyInterestRate: 0.02,
        fullPayoffFeeRate: 0.1,
        fullPayoffFeeFreeDay: 10,
        autoRepayRatio: 0.2,
        quickAmounts: [10, 50, 100],
        warningDebt: 1000,
        loanLimitStep: 300,
        minCreditTier: -2,
        maxCreditTier: 3,
        strongRepayInterestDays: 2,
        highRiskInterestDays: 6,
      },
      shop: {
        discountStartHour: 20,
        discountEndHour: 22,
        dailyOfferCount: 3,
        discountRates: [0.15, 0.2, 0.25, 0.3, 0.35],
        consumableStockRange: [2, 5],
        furnitureStockRange: [1, 1],
      },
      lottery: {
        ticketPrice: 20,
        jackpotBase: 1000000,
        drawDigits: 6,
        retryCooldownMs: 30000,
        prizeRewards: {
          second_prize: 20000,
          third_prize: 2000,
          fourth_prize: 200,
          fifth_prize: 20,
        },
      },
      catDecayRules: {
        hunger: { intervalMs: 12 * 60 * 1000, label: "饱腹" },
        clean: { intervalMs: 8 * 60 * 1000, label: "清洁" },
        mood: { intervalMs: 6 * 60 * 1000, label: "心情" },
        health: { intervalMs: 10 * 60 * 1000, label: "健康" },
        energy: { intervalMs: 5 * 60 * 1000, label: "活力" },
      },
    },
    data: {},
    utils: {},
    state: {
      game: null,
      currentPage: "home",
      selectedCatId: "cat_001",
      notifications: [],
      arcadeSpin: null,
      roomDrag: null,
      collectionInspectCatId: null,
      lotteryDraftDigits: ["0", "0", "0", "0", "0", "0"],
      lotteryCelebration: null,
      lotteryHistoryDrawDate: null,
    },
    systems: {},
    ui: {},
  };
})();
