(function () {
  window.CatGame = window.CatGame || {
    config: {
      storageKey: "catGameSaveV1",
      version: "1.15.0",
      startingFurniture: ["bed_basic", "bowl_basic"],
      releaseNotes: {
        "zh-CN": [
          "整体界面改成更温暖可爱的田园风格，并把主要功能模块导航统一放到了游戏上方。",
          "新增银行模块，可进行存款、取款、贷款与还款，所有金融数据都保存在本地存档中。",
          "贷款会按游戏内天数累计利息，打工收入还会自动抽取一部分用于还贷。",
          "银行页现在会显示下次存款利息与贷款利息的结算时间和预计金额，并支持一键还清贷款。",
          "贷款可借上限会根据以往还款表现动态变化，按时还清会更容易获得更高额度。",
          "新增提前一次性还清贷款手续费，刚贷款时最高为贷款本金的 10%，到第 10 天降为 0%。",
          "各页面介绍区域已缩小，让主要功能内容更靠上、更省空间。",
          "商店新增晚间 20:00-22:00 随机限时折扣，库存卖完后会恢复原价。",
          "任务系统新增银行相关成就，分别对应存款达 1 万和累计贷款达 2 万。",
          "打工新增 Lv.10 解锁职业「猫咖管理员」，30 分钟高收益高消耗。",
          "游戏厅新增本地单机彩票玩法，可手选或随机购买 6 位号码彩票。",
          "彩票每天按 UTC 日期开奖，开奖结果基于比特币区块哈希，并支持奖池滚存。",
        ],
        en: [
          "The UI now uses a softer cozy village look, and major feature modules have been moved into a top navigation bar.",
          "Added a Bank module with deposit, withdraw, loan, and repayment actions, all saved locally.",
          "Loans now accrue interest by in-game day, and work income can automatically repay part of your debt.",
          "The Bank page now shows the next savings payout and loan interest charge preview, and adds one-tap full payoff.",
          "Future loan limits now change based on how responsibly previous loans were repaid.",
          "Early full loan payoff now has a fee that starts at 10% and fades to 0% by day 10.",
          "Large page introductions have been scaled down so the main content appears sooner.",
          "The shop now runs random limited evening discounts from 20:00 to 22:00, and sold-out deals return to normal price.",
          "New bank achievements now reward you for reaching 10,000 in savings and 20,000 in total borrowing.",
          "Added the level 10 job 'Cat Cafe Manager' with higher cost and higher reward.",
          "Added a local single-player lottery feature inside the Arcade, with manual and random 6-digit tickets.",
          "The lottery resolves by UTC date, derives results from Bitcoin block hashes, and supports jackpot rollover.",
        ],
        ja: [
          "UI全体をよりかわいい田園風デザインに刷新し、主要機能のナビゲーションを上部へ移動しました。",
          "預金・引き出し・ローン・返済に対応した銀行モジュールを追加しました。",
          "ローンはゲーム内日数で利息が増え、仕事収入の一部は自動返済に使われます。",
          "銀行ページに次回の預金利息・ローン利息の予定表示と、一括返済ボタンを追加しました。",
          "返済状況に応じて次回の借入上限が上下するようになりました。",
          "ローン直後の一括返済には手数料がかかり、10日目で 0% まで下がるようになりました。",
          "各ページの紹介エリアを縮小し、主要な機能がより上に見えるようにしました。",
          "ショップに 20:00-22:00 のランダム夜間セールを追加し、売り切れ後は通常価格に戻ります。",
          "銀行関連の実績を追加し、預金 1 万と累計借入 2 万で報酬を獲得できるようになりました。",
          "Lv.10 で解放される新しい仕事「猫カフェ管理人」を追加しました。",
          "ゲームセンターにローカル単機用の宝くじ機能を追加し、手動またはランダムで 6 桁の券を購入できます。",
          "宝くじは UTC 日付ごとに抽選され、ビットコインのブロックハッシュから当選番号を生成し、ジャックポット繰り越しにも対応します。",
        ],
      },
      readoptCost: 80,
      toyWandUsesPerPurchase: 6,
      catUnlockRequirements: {
        gold: 5000,
        baseCatId: "cat_001",
        baseAgeYears: 1,
      },
      catAgeAcceleration: 10,
      pregnancyDurationMs: 30 * 60 * 1000,
      pregnancyFoodMultiplier: 2,
      roomUpgradeSteps: [
        { level: 1, capacity: 3, width: 620, height: 360, upgradeCost: 450 },
        { level: 2, capacity: 4, width: 760, height: 420, upgradeCost: 900 },
        { level: 3, capacity: 5, width: 900, height: 500, upgradeCost: 1600 },
        { level: 4, capacity: 6, width: 1020, height: 580, upgradeCost: null },
      ],
      diseaseCheckIntervalMs: 15 * 60 * 1000,
      staminaRecoveryIntervalMs: 60 * 60 * 1000,
      staminaRecoveryAmount: 5,
      customMusicMaxBytes: 2 * 1024 * 1024,
      slotBets: [20, 50, 100],
      playerCondition: {
        min: 0,
        max: 100,
        defaultStamina: 100,
        defaultMood: 80,
        defaultHunger: 20,
        hungerBlockThreshold: 80,
        hungerIncreaseIntervalMs: 15 * 60 * 1000,
        hungerIncreaseAmount: 4,
        sleepRecoveryPerHour: {
          stamina: 20,
          mood: 20,
        },
        workMoodThresholds: {
          normal: 60,
          tired: 30,
        },
        workMoodModifiers: {
          normal: {
            durationMultiplier: 1,
            penaltyChance: 0,
            penaltyRange: [0, 0],
          },
          tired: {
            durationMultiplier: 1.25,
            penaltyChance: 0,
            penaltyRange: [0, 0],
          },
          burnedOut: {
            durationMultiplier: 1.5,
            penaltyChance: 0.2,
            penaltyRange: [0.1, 0.2],
          },
        },
        moodLevels: [
          { min: 80, key: "player_mood_very_good", tone: "is-good" },
          { min: 60, key: "player_mood_good", tone: "is-success" },
          { min: 30, key: "player_mood_tired", tone: "is-warning" },
          { min: 0, key: "player_mood_burned_out", tone: "is-danger" },
        ],
      },
      bank: {
        minLoanAmount: 100,
        maxLoanAmount: 2000,
        savingsDailyRate: 0.01,
        dailyInterestRate: 0.02,
        fullPayoffFeeRate: 0.1,
        fullPayoffFeeFreeDay: 10,
        autoRepayRatio: 0.2,
        quickAmounts: [10, 50, 100],
        warningDebt: 1000,
        loanLimitStep: 300,
        minCreditTier: -2,
        maxCreditTier: 3,
        strongRepayInterestDays: 2,
        highRiskInterestDays: 6,
      },
      shop: {
        discountStartHour: 20,
        discountEndHour: 22,
        dailyOfferCount: 3,
        discountRates: [0.15, 0.2, 0.25, 0.3, 0.35],
        consumableStockRange: [2, 5],
        furnitureStockRange: [1, 1],
      },
      lottery: {
        ticketPrice: 20,
        jackpotBase: 1000000,
        drawDigits: 6,
        retryCooldownMs: 30000,
        prizeRewards: {
          second_prize: 20000,
          third_prize: 2000,
          fourth_prize: 200,
          fifth_prize: 20,
        },
      },
      catDecayRules: {
        hunger: { intervalMs: 12 * 60 * 1000, label: "饱腹" },
        clean: { intervalMs: 8 * 60 * 1000, label: "清洁" },
        mood: { intervalMs: 6 * 60 * 1000, label: "心情" },
        health: { intervalMs: 10 * 60 * 1000, label: "健康" },
        energy: { intervalMs: 5 * 60 * 1000, label: "活力" },
      },
    },
    data: {},
    utils: {},
    state: {
      game: null,
      currentPage: "home",
      selectedCatId: "cat_001",
      notifications: [],
      arcadeSpin: null,
      roomDrag: null,
      collectionInspectCatId: null,
      lotteryDraftDigits: ["0", "0", "0", "0", "0", "0"],
    },
    systems: {},
    ui: {},
  };
})();
